# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='review_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
