# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20170509_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='doc1description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='doc2description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='doc3description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='doc4description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='doc5description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='doc6description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
